/**
 * Export Manager
 *
 * Exports sheets and parts to SVG, DXF, PDF-ready, and laser-ready formats.
 */

import type { Sheet, NestedPlacement, CutOrderPlan, CutInstruction } from "@/types/manufacturing";

/** Export sheets as SVG */
export function exportSheetsSVG(sheets: Sheet[]): string[] {
  return sheets.map((sheet) => {
    let svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${sheet.width}" height="${sheet.height}" viewBox="0 0 ${sheet.width} ${sheet.height}">\n`;
    svg += `  <rect width="${sheet.width}" height="${sheet.height}" fill="#f8f8f8" stroke="#ccc"/>\n`;

    for (const p of sheet.placements) {
      svg += `  <rect x="${p.x}" y="${p.y}" width="${p.width}" height="${p.height}" fill="none" stroke="#ff0000" stroke-width="1"`;
      if (p.rotation) svg += ` transform="rotate(${p.rotation} ${p.x + p.width / 2} ${p.y + p.height / 2})"`;
      svg += `/>\n`;
      svg += `  <text x="${p.x + 5}" y="${p.y + 14}" font-size="10" fill="#333">${p.partNumber}</text>\n`;
    }

    svg += `</svg>`;
    return svg;
  });
}

/** Export as DXF (minimal DXF format) */
export function exportSheetsDXF(sheets: Sheet[]): string[] {
  return sheets.map((sheet) => {
    let dxf = "0\nSECTION\n2\nHEADER\n0\nENDSEC\n0\nSECTION\n2\nENTITIES\n";
    for (const p of sheet.placements) {
      const x1 = p.x, y1 = sheet.height - p.y;
      const x2 = p.x + p.width, y2 = sheet.height - p.y - p.height;
      dxf += `0\nLIGHTWEIGHTPOLYLINE\n8\n0\n90\n4\n70\n1\n`;
      dxf += `10\n${x1}\n20\n${y1}\n`;
      dxf += `10\n${x2}\n20\n${y1}\n`;
      dxf += `10\n${x2}\n20\n${y2}\n`;
      dxf += `10\n${x1}\n20\n${y2}\n`;
    }
    dxf += "0\nENDSEC\n0\nEOF";
    return dxf;
  });
}

/** Generate laser-ready G-code (simplified Ruida/LightBurn compatible) */
export function exportLaserGCode(
  sheets: Sheet[],
  cutPlan: CutOrderPlan,
): string[] {
  return sheets.map((sheet, si) => {
    const sheetInstrs = cutPlan.instructions;
    const lines: string[] = [
      `; Laser Cut File - Sheet ${si + 1}`,
      `; Generated by Ramesh Art Designer Pro`,
      `G21 ; mm mode`,
      `G90 ; absolute positioning`,
      `M4 ; laser on`,
      ``,
    ];

    for (const instr of sheetInstrs) {
      const speed = Math.round(instr.speed * 60); // mm/s → mm/min
      lines.push(`; ${instr.partNumber} - ${instr.action}`);
      lines.push(`G0 X0 Y0 ; rapid to origin`);
      lines.push(`M3 S${Math.round(instr.power * 1.1)} ; laser power`);
      lines.push(`G1 F${speed}`);
      // Simplified path - just draw the bounding rect for now
      const parts = instr.path.match(/[\d.]+/g);
      if (parts) {
        for (let i = 0; i < parts.length; i += 2) {
          const x = parseFloat(parts[i]!);
          const y = parseFloat(parts[i + 1]!);
          if (i === 0) lines.push(`G0 X${x.toFixed(2)} Y${y.toFixed(2)}`);
          else lines.push(`G1 X${x.toFixed(2)} Y${y.toFixed(2)}`);
        }
      }
      lines.push(`M5 ; laser off`);
    }

    lines.push(``);
    lines.push(`M5 ; laser off`);
    lines.push(`G0 X0 Y0`);
    lines.push(`M30 ; program end`);
    return lines.join("\n");
  });
}

/** Generate cut-ready SVG with color-coded layers */
export function exportCutReadySVG(
  sheets: Sheet[],
  cutPlan: CutOrderPlan,
  mappings: { color: string; action: string; layerName: string; label?: string }[],
): string[] {
  return sheets.map((sheet) => {
    const layerGroup = (action: string) => {
      const mapping = mappings.find((m) => m.action === action);
      return mapping ? mapping.layerName : action;
    };

    let svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${sheet.width}" height="${sheet.height}">\n`;
    svg += `  <defs>\n`;

    for (const m of mappings) {
      svg += `    <g id="layer-${m.layerName}"><title>${m.label}</title></g>\n`;
    }
    svg += `  </defs>\n`;
    svg += `  <rect width="${sheet.width}" height="${sheet.height}" fill="#fff"/>\n`;

    for (const p of sheet.placements) {
      const mapping = mappings.find((m) => m.color === "#ff0000") || mappings[0];
      if (!mapping) continue;
      svg += `  <rect x="${p.x}" y="${p.y}" width="${p.width}" height="${p.height}" fill="none" stroke="${mapping.color}" stroke-width="1" class="${layerGroup(mapping.action)}"/>\n`;
    }

    svg += `</svg>`;
    return svg;
  });
}
